# Generated by Django 2.2.14 on 2020-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Amor'), ('SW', 'Especiales'), ('OW', 'San Valentín'), ('PM', 'Te amo mamá')], max_length=2),
        ),
    ]
